spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgresuser
    password: securepassword
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  mvc:
    throw-exception-if-no-handler-found: true
    async:
      request-timeout: 3600000
server:
  port: 8081
  error:
    path: /user/error
    whitelabel:
      enabled: true

logging:
  level:
    root: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    org.springframework.data.jpa: DEBUG

jwt:
  secret: achatapp
app:
  jwttoken:
    message: this is the token
